Fish forces REVIEW NEEDED
fredrikm/SoCSProject16 pull request #15
Opened 2016-11-21 16:33 UTC by kognitiva

Add fish forces to velocity update

2016-11-22 07:56 UTC, rasake commented on code/agents.py
> +    def get_neighbours(self):
Good move to have this in dedicated function, improves readability. But change name to find_neighbours, there are no getters in Python.

2016-11-22 07:56 UTC, rasake commented on code/agents.py
> +        neighbours = self.get_neighbours()
Assume neigbours are already found by think(), just get them directly from the attribute self.neighbouring_fish. That way we don't have to do the search twice.

2016-11-22 07:56 UTC, rasake commented on code/agents.py
> +    def get_fish_forces(self):
Don't use get in python method names. Call it something else like "calculate_fish_forces", or make it a property using the @property decorator.

2016-11-22 07:56 UTC, rasake commented on code/main.py
> +        self.k = 1
Did you intend to put this attributes in each fish instance? Then they must be indented as part of the for loop and it should be fish.k = 1, fish.power=6, in that case I believe.

2016-11-22 07:59 UTC, kognitiva commented on code/main.py
> +        self.k = 1
No. It's part of the environment. Makes more sense that physics is part of the environment right?

2016-11-22 10:37 UTC, rasake commented on code/main.py
> +        self.k = 1
I see.

2016-11-22 14:28 UTC, rasake requested changes

2016-11-22 14:28 UTC, rasake commented on code/agents.py
> +            f_i = k / np.abs(fish.position-self.position)**power
f_i should be directed as rel. distanc vector between fish and have magnitude inversely proport. to (norm of rel. distance)^power

2016-11-22 19:31 UTC, kognitiva commented
@rasake I fixed the fish forces now! I set the parameters very high to make sure that it was doing its job. I guess we have to run some optimization before we know what we level of force we need to get nice results.

2016-11-23 08:52 UTC, rasake commented
Funkar kraften nu?

2016-11-23 11:13 UTC, merged