Simple implementation of multilayer FFN, with some unit tests
fredrikm/SoCSProject16 pull request #2
Opened 2016-11-18 09:37 UTC by rasake

2016-11-18 14:52 UTC, kognitiva commented
hur testkör jag den här koden?

2016-11-18 17:42 UTC, reinthal requested changes
1. Skulle vilja ha kommentarer på vad testerna gör i detalj. Just nu vet jag inte vad dom testar
2. Kan du göra ett test som också tränar nätverket på samma sätt som vi gjorde i 4b först inlämningen i ann?

2016-11-18 19:31 UTC, rasake commented
1. Ska lägga in  lite kommentarer, återkommer.

2. I vårt fall kommer träningen skötas av PSO:n, så ingen idé att skriva kod för backpropogation

2016-11-18 21:36 UTC, rasake commented
Jag lade till lite kommentarer, förhoppningsvis blir det lite tydligare nu.

2016-11-19 07:23 UTC, kognitiva commented
Nice! Bra kommentarer på unittesterna. Nu ser det ut som att det finns back-propagation i feed_forward_network.py ändå men inga tester till den. Den filen kanske skall tas bort om den inte skall användas.

2016-11-19 08:07 UTC, rasake commented
Ah, just det, den feed_forward.py var bara ett exempel ändå. plockar bort den på en gång.

2016-11-20 18:38 UTC, merged